### ISSUE TITLE
数据显示问题

### ISSUE THREAD

**Issue by yanyueWorld** [airyland/china-area-data#14]
不知道大家遇到没有，我代码如下：
<el-cascader size="large" :options="options" v-model="selectedOptions" @change="handleChange" placeholder="请选择地区" clearable>
</el-cascader>
handleChange(value){
		window.console.log(value);
		// for(var i=0;i<value.length;i++){
		// 	this.selectedOptions[i]=CodeToText[value[i]];
		// }
		// window.console.log(this.selectedOptions);
}
注释的代码是为了转换编码为中文地域名，结果是，转换了，控制台能获取到，但是页面下拉框没有选择信息，显示问题，不转换呢，控制台获取编码，页面显示中文地域名信息，显示没问题。

**Comment by airyland** [comment]
本 repo 不解决具体数据调用问题，再说你连代码都没写清楚，跟本 repo 没有任何关联。
