### ISSUE TITLE
三级联动数据后台更新

### ISSUE THREAD

**Issue by xuchlei** [airyland/china-area-data#18]
数据好久没有更新了，感觉现在用不是很友好。
可以从国务院-民政部来获取最新的[行政区划代码](http://www.mca.gov.cn/article/sj/xzqh/)数据。
操做方法可以参考[Vue-element-china-area-data-数据源修改](https://xuchunlei.top/2020/06/19/Vue-element-china-area-data-%E6%95%B0%E6%8D%AE%E6%BA%90%E4%BF%AE%E6%94%B9/)。

**Comment by airyland** [comment]
收到，我会尽快更新一个版本。

**Comment by airyland** [comment]
done.
