### ISSUE TITLE
雄安不作为单独的区域可选择吗？

### ISSUE THREAD

**Issue by mqliutie** [airyland/china-area-data#2]
雄安新区是中国第19个国家级新区，也是首个由中共中央、国务院印发通知成立的国家级新区，位于河北省保定市东部，由雄县、容城县、安新县及其周边部分地区组成[1]，于2017年4月1日正式成立。

现在这三个地区都单独存在

**Comment by airyland** [comment]
统计局最新数据是16年的，内置地址遵照官方数据更新。看了下京东的地址选择也并没有引入该区。

**Comment by chung8981** [comment]
深圳市新设立了龙华区和坪山区。

**Comment by airyland** [comment]
国家统计局的数据还没有单独列出雄安，所以暂时不是单独的区域。
