### ISSUE TITLE
湖北省的数据需要更新了

### ISSUE THREAD

**Issue by dwqs** [airyland/china-area-data#3]
原属湖北省下的仙桃市、潜江市、天门市和神农架林区 被划分到 省直辖县级行政区划 之下了：http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2016/42.html

**Comment by airyland** [comment]
发现统计局把原来的列表页删除了。。要重新写采集规则了。

**Comment by dwqs** [comment]
@airyland 看了淘宝、京东的地区选择  都会忽略「省直辖县级行政区划」 依然把 仙桃市、潜江市、天门市和神农架林区放在二级  更新后的数据是否也考虑这样编排数据格式？

**Comment by airyland** [comment]
直接放在二级似乎是比较合理的做法，不然用户会容易找不到。

**Comment by airyland** [comment]
updated on v5.
