### ISSUE TITLE
兄弟，不能设计成树形结构吗

### ISSUE THREAD

**Issue by LaamGinghong** [airyland/china-area-data#7]

**Comment by airyland** [comment]
已经提供数组格式。如果是需要多层嵌套也可以简单转换下。

**Comment by huxianguan** [comment]
`const china = require('./china.json')
const fs = require("fs");

const getChild = (parentCode) => {
  const areaArr = []
  Object.keys(china[parentCode]).forEach(code => {
    const item = {
      text: china[parentCode][code],
      value: code
    }
    if (china[code]) {
      const children = getChild(code, areaArr);
      item.children = children;
    }
    areaArr.push(item);
  })
  return areaArr;
}

const all = getChild('86');

fs.writeFileSync('chinaArea.json', JSON.stringify(all));`

china.json 用的是里面的这个: 
![image](https://user-images.githubusercontent.com/18564236/121275408-323ce780-c8ff-11eb-9f8d-cc6dc91dbc7e.png)
